ANTIDELETE=TRUE 
AUTO_READ=true 
AUTO_REACT=true 
AUTO_REJECT_ENABLED=true 
AUTO_VIEW_STATUS=true 
BOT_NAME=UNBANNED TECH 
MODE=PUBLIC 
OWNER_NAME=UNBANNED 
OWNER_NUMBER=263776695994
PRESENCE_STATUS=true 
PREFIX=.
SESSION_ID=
